apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-web
        image: aida2302/my-app_web
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            port: 5000
            path: /
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 5000
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5