apiVersion: v1
kind: Secret
metadata:
  name: simple-app-secret
type: Opaque
data:
  DATABASE_URI: { { printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.externalPostgresql.postgresqlUsername .Values.externalPostgresql.postgresqlPassword .Values.externalPostgresql.postgresqlHost .Values.externalPostgresql.postgresqlPort .Values.externalPostgresql.postgresqlDatabase | b64enc | quote } }
  POSTGRES_DB: { { .Values.externalPostgresql.postgresqlDatabase | b64enc } }
  POSTGRES_PASSWORD: { { .Values.externalPostgresql.postgresqlPassword | b64enc } }
  POSTGRES_USER: { { .Values.externalPostgresql.postgresqlUsername | b64enc } }