apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: {{ .Values.image }}
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: simple-app-secret
                  key: DATABASE_URI
          ports:
            - containerPort: 5000