apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
  labels:
    app: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: simple-app:v1
        env:
          - name: DATABASE_URI
            value: "postgresql+psycopg2://test:test@postgres:5432/test"
        ports:
        - containerPort: 5000