apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: simple-app
build:
  artifacts:
  - image: simple-app
    context: app
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment-env.yaml
    - service.yaml
